In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1) Read the dataset 

In [2]:
data=pd.read_csv('C:\\Users\\Sweety\\Desktop\\anjali\\Machine Learning Internship\\amazon_alexa.csv')
data

Unnamed: 0  precision    recall  f1-score  support
0             0   1.000000  1.000000  1.000000    19.00
1             1   0.950000  0.904762  0.926829    21.00
2             2   0.904762  0.950000  0.926829    20.00
3      accuracy   0.950000  0.950000  0.950000     0.95
4     macro avg   0.951587  0.951587  0.951220    60.00
5  weighted avg   0.950754  0.950000  0.950000    60.00

In [3]:
data.head()

Unnamed: 0  precision    recall  f1-score  support
0          0   1.000000  1.000000  1.000000    19.00
1          1   0.950000  0.904762  0.926829    21.00
2          2   0.904762  0.950000  0.926829    20.00
3   accuracy   0.950000  0.950000  0.950000     0.95
4  macro avg   0.951587  0.951587  0.951220    60.00

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  6 non-null      object 
 1   precision   6 non-null      float64
 2   recall      6 non-null      float64
 3   f1-score    6 non-null      float64
 4   support     6 non-null      float64
dtypes: float64(4), object(1)
memory usage: 368.0+ bytes


In [5]:
data.describe()

precision    recall  f1-score    support
count   6.000000  6.000000  6.000000   6.000000
mean    0.951184  0.951058  0.950813  30.158333
std     0.030137  0.030141  0.026726  24.272421
min     0.904762  0.904762  0.926829   0.950000
25%     0.950000  0.950000  0.932622  19.250000
50%     0.950377  0.950000  0.950000  20.500000
75%     0.951379  0.951190  0.950915  50.250000
max     1.000000  1.000000  1.000000  60.000000

In [6]:
data.shape

(6, 5)

# 2) Remove handle null values (if any)

In [7]:
data.isnull()

Unnamed: 0  precision  recall  f1-score  support
0       False      False   False     False    False
1       False      False   False     False    False
2       False      False   False     False    False
3       False      False   False     False    False
4       False      False   False     False    False
5       False      False   False     False    False

In [8]:
data.isnull().sum()

Unnamed: 0    0
precision     0
recall        0
f1-score      0
support       0
dtype: int64

# 3) Preprocess the Amazon Alexa reviews based on the following parameter:

# a) Tokenizing words

In [9]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [10]:
import nltk

In [11]:
from nltk.tokenize import TreebankWordTokenizer
sentence = "Sometimes while playing a game, you can answer..."
tokenizer = TreebankWordTokenizer()
tokenizer.tokenize(sentence)

['Sometimes',
 'while',
 'playing',
 'a',
 'game',
 ',',
 'you',
 'can',
 'answer',
 '...']

In [12]:
data

Unnamed: 0  precision    recall  f1-score  support
0             0   1.000000  1.000000  1.000000    19.00
1             1   0.950000  0.904762  0.926829    21.00
2             2   0.904762  0.950000  0.926829    20.00
3      accuracy   0.950000  0.950000  0.950000     0.95
4     macro avg   0.951587  0.951587  0.951220    60.00
5  weighted avg   0.950754  0.950000  0.950000    60.00

# b) Convert words to lower case

In [13]:
my_word="I have had a lot of fun with this thing."
print(my_word)

I have had a lot of fun with this thing.


In [14]:
lower=my_word.lower()
print(lower)

i have had a lot of fun with this thing.


# c) Removing Punctuations

In [15]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [16]:
import string
regular_punct = list(string.punctuation)
def remove_punctuation(text,punct_list):
    for punc in punct_list:
        if punc in text:
            text = text.replace(punc, ' ')
    return text.strip()

remove_punctuation("Love my Echo! ",regular_punct)

'Love my Echo'

# d) Removing Stop words

In [17]:
pip install nltk

Note: you may need to restart the kernel to use updated packages.


In [18]:
import nltk

In [19]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [20]:
import nltk
from nltk.corpus import stopwords
print(stopwords.words('english'))

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [21]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
text = "I sent it to my 85 year old Dad, and he talks to it constantly."
text_tokens = word_tokenize(text)
tokens_without_sw = [word for word in text_tokens if not word in stopwords.words()]
print(tokens_without_sw)

['I', '85', 'year', 'Dad', ',', 'talks', 'constantly', '.']


# e) Stemming or lemmatizing the words

In [22]:
import nltk

In [23]:
nltk.download



<bound method Downloader.download of <nltk.downloader.Downloader object at 0x0000023AB6CD5310>>

In [24]:
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer


In [25]:
#create an object of class PorterStemmer
porter = PorterStemmer()
lancaster=LancasterStemmer()
#proide a word to be stemmed
print("Porter Stemmer")
print(porter.stem("cats"))
print(porter.stem("trouble"))
print(porter.stem("troubling"))
print(porter.stem("troubled"))
print("Lancaster Stemmer")
print(lancaster.stem("cats"))
print(lancaster.stem("trouble"))
print(lancaster.stem("troubling"))
print(lancaster.stem("troubled"))


Porter Stemmer
cat
troubl
troubl
troubl
Lancaster Stemmer
cat
troubl
troubl
troubl


In [26]:
#A list of words to be stemmed
word_list = ["friend", "friendship", "friends", "friendships","stabil","destabilize","misunderstanding","railroad","moonlight","football"]
print("{0:20}{1:20}{2:20}".format("Word","Porter Stemmer","lancaster Stemmer"))
for word in word_list:
    print("{0:20}{1:20}{2:20}".format(word,porter.stem(word),lancaster.stem(word)))


Word                Porter Stemmer      lancaster Stemmer   
friend              friend              friend              
friendship          friendship          friend              
friends             friend              friend              
friendships         friendship          friend              
stabil              stabil              stabl               
destabilize         destabil            dest                
misunderstanding    misunderstand       misunderstand       
railroad            railroad            railroad            
moonlight           moonlight           moonlight           
football            footbal             footbal             


In [27]:
sentence="Sometimes while playing a game, you can answer a question correctly but Alexa says you got it wrong and answers the same as you."
porter.stem(sentence)


'sometimes while playing a game, you can answer a question correctly but alexa says you got it wrong and answers the same as you.'

In [28]:
from nltk.tokenize import sent_tokenize, word_tokenize
def stemSentence(sentence):
    token_words=word_tokenize(sentence)
    token_words
    stem_sentence=[]
    for word in token_words:
        stem_sentence.append(porter.stem(word))
        stem_sentence.append(" ")
    return "".join(stem_sentence)

x=stemSentence(sentence)
print(x)


sometim while play a game , you can answer a question correctli but alexa say you got it wrong and answer the same as you . 


In [29]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
print("rocks :", lemmatizer.lemmatize("rocks"))
print("corpora :", lemmatizer.lemmatize("corpora"))
print("better :", lemmatizer.lemmatize("better", pos ="a"))


rocks : rock
corpora : corpus
better : good


# 4)Transform the words into vectors using
     a)Count Vectorizer OR
     b)TF-IDF Vectorizer

# a)Count Vectorizer

In [30]:
from sklearn.feature_extraction.text import CountVectorizer

document = ["Really happy with this purchase great speaker and easy to set up.",
            "We love the size of the 2nd generation echo. Still needs a little improvement on sound", 
            "I like it"]
vectorizer = CountVectorizer()
vectorizer.fit(document)
# Printing the identified Unique words along with their indices
print("Vocabulary: ", vectorizer.vocabulary_)
# Encode the Document
vector = vectorizer.transform(document)
# Summarizing the Encoded Texts
print("Encoded Document is:")
print(vector.toarray())


Vocabulary:  {'really': 16, 'happy': 6, 'with': 27, 'this': 23, 'purchase': 15, 'great': 5, 'speaker': 20, 'and': 1, 'easy': 2, 'to': 24, 'set': 17, 'up': 25, 'we': 26, 'love': 11, 'the': 22, 'size': 18, 'of': 13, '2nd': 0, 'generation': 4, 'echo': 3, 'still': 21, 'needs': 12, 'little': 10, 'improvement': 7, 'on': 14, 'sound': 19, 'like': 9, 'it': 8}
Encoded Document is:
[[0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 1 0 0 1 1 1 0 1]
 [1 0 0 1 1 0 0 1 0 0 1 1 1 1 1 0 0 0 1 1 0 1 2 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


# b)TF-IDF Vectorizer

In [31]:
text=["Sometimes while playing a game, you can answer a question correctly but Alexa says you got it wrong and answers the same as you",
      "I like being able to turn lights on and off while away from home."]

In [32]:
text

['Sometimes while playing a game, you can answer a question correctly but Alexa says you got it wrong and answers the same as you',
 'I like being able to turn lights on and off while away from home.']

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer=TfidfVectorizer(lowercase=True,stop_words='english')
vector1=vectorizer.fit_transform(text)
features1=vectorizer.get_feature_names()

C:\Users\Sweety\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [34]:
import pandas as pd
pd.DataFrame(vector1.toarray(),columns=vectorizer.get_feature_names())

able     alexa    answer   answers      away  correctly      game  \
0  0.000000  0.316228  0.316228  0.316228  0.000000   0.316228  0.316228   
1  0.408248  0.000000  0.000000  0.000000  0.408248   0.000000  0.000000   

        got      home    lights      like   playing  question      says  \
0  0.316228  0.000000  0.000000  0.000000  0.316228  0.316228  0.316228   
1  0.000000  0.408248  0.408248  0.408248  0.000000  0.000000  0.000000   

       turn     wrong  
0  0.000000  0.316228  
1  0.408248  0.000000

In [35]:
print(vectorizer.idf_)

[1.40546511 1.40546511 1.40546511 1.40546511 1.40546511 1.40546511
 1.40546511 1.40546511 1.40546511 1.40546511 1.40546511 1.40546511
 1.40546511 1.40546511 1.40546511 1.40546511]


# 5) Split data into training and test data.

In [36]:
# import modules
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# read the dataset
#df = pd.read_csv()
data=pd.read_csv('C:\\Users\\Sweety\\Desktop\\anjali\\Machine Learning Internship\\amazon_alexa.csv')
data

Unnamed: 0  precision    recall  f1-score  support
0             0   1.000000  1.000000  1.000000    19.00
1             1   0.950000  0.904762  0.926829    21.00
2             2   0.904762  0.950000  0.926829    20.00
3      accuracy   0.950000  0.950000  0.950000     0.95
4     macro avg   0.951587  0.951587  0.951220    60.00
5  weighted avg   0.950754  0.950000  0.950000    60.00

In [37]:
# get the locations
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

# split the dataset
X_train, X_test, y_train, y_test = train_test_split(
  X, y, test_size=0.05, random_state=0)

In [38]:
print(X_train)


  Unnamed: 0  precision    recall  f1-score
2          2   0.904762  0.950000  0.926829
1          1   0.950000  0.904762  0.926829
3   accuracy   0.950000  0.950000  0.950000
0          0   1.000000  1.000000  1.000000
4  macro avg   0.951587  0.951587  0.951220


In [39]:
print(y_train)

2    20.00
1    21.00
3     0.95
0    19.00
4    60.00
Name: support, dtype: float64


In [40]:
X_test

Unnamed: 0  precision  recall  f1-score
5  weighted avg   0.950754    0.95      0.95

In [41]:
y_test

5    60.0
Name: support, dtype: float64

# 6) Apply the following models on the training dataset and generate the predicted value for the test dataset

# a) Multinomial Naïve Bayes Classification

In [42]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
from sklearn import metrics
print("Gaussian Naive Bayes model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)


Gaussian Naive Bayes model accuracy(in %): 95.0


# b) Logistic Regression

In [43]:
from sklearn.linear_model import LogisticRegression
a = LogisticRegression(max_iter=1000000,solver='liblinear')
a.fit(X_train,y_train)


LogisticRegression(max_iter=1000000, solver='liblinear')

In [44]:
def mscore(model):
    print('Training score',model.score(X_train,y_train))
    print('Training score',model.score(X_test,y_test))

In [45]:
mscore(a)

Training score 0.9555555555555556
Training score 0.9


In [57]:
from sklearn.metrics import confusion_matrix,classification_report
def eval_mode(ytest,ypred):
    cm=confusion_matrix(ytest,ypred)
    print(cm)
    print(classification_report(ytest,ypred))

In [58]:
ypred_a=a.predict(X_test)
eval_model(y_test,ypred_a)

[[19  0  0]
 [ 0 16  5]
 [ 0  1 19]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.94      0.76      0.84        21
           2       0.79      0.95      0.86        20

    accuracy                           0.90        60
   macro avg       0.91      0.90      0.90        60
weighted avg       0.91      0.90      0.90        60



# c) KNN Classification

In [59]:
from sklearn.neighbors import KNeighborsClassifier

In [60]:
b=KNeighborsClassifier(n_neighbors=23)
b.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=23)

In [61]:
mscore(b)

Training score 0.9444444444444444
Training score 0.9833333333333333


In [62]:
ypred_b=b.predict(X_test)
eval_model(y_test,ypred_b)

[[19  0  0]
 [ 0 20  1]
 [ 0  0 20]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.95      0.98        21
           2       0.95      1.00      0.98        20

    accuracy                           0.98        60
   macro avg       0.98      0.98      0.98        60
weighted avg       0.98      0.98      0.98        60



# 7) Predict the feedback for test data

In [63]:
y_test

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 2, 2,
       1, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1])

In [64]:
#data['sentiment'].value_counts()


In [65]:
pip install wordcloud

Note: you may need to restart the kernel to use updated packages.


In [71]:
pred = dtc.predict(X_test)
pred
from sklearn.metrics import accuracy_score, confusion_matrix
dtc_acc = accuracy_score(pred,y_test)
print(dtc_acc)
print(confusion_matrix(pred,y_test))



0.9666666666666667
[[19  0  0]
 [ 0 20  1]
 [ 0  1 19]]


In [70]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train , y_train)
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)
pred=model.predict(X_test)
print(accuracy_score(y_test,pred))


0.9666666666666667


In [ ]:
from sklearn import metrics
cm = confusion_matrix(y_test,pred)

cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = cm,display_labels = [False, True])

cm_display.plot()
plt.show()



In [ ]:
pip install matplotlib==3.2.0

# 8) Compute Confusion matrix and classification report for each of these models

In [72]:
from sklearn.metrics import accuracy_score, confusion_matrix
dtc_acc = accuracy_score(pred,y_test)
print(dtc_acc)
print(confusion_matrix(pred,y_test))

0.9666666666666667
[[19  0  0]
 [ 0 20  1]
 [ 0  1 19]]


In [73]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# 9)Report the model with the best accuracy

In [74]:
from sklearn.svm import SVC
knn=SVC()
knn.fit(X_train,y_train)


SVC()

In [75]:
pred1 = knn.predict(X_test)
pred1

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 2, 2,
       1, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1])

In [79]:
pred2 = knn.predict(X_train)
pred2

array([0, 2, 2, 0, 0, 2, 0, 2, 2, 1, 1, 2, 2, 0, 1, 1, 2, 1, 2, 1, 0, 0,
       0, 2, 0, 2, 2, 2, 0, 0, 1, 0, 2, 1, 2, 2, 1, 2, 2, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 2, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 2, 0, 0, 2, 1, 2, 1, 2, 2, 2,
       2, 0])

In [81]:
from sklearn.metrics import accuracy_score
svc_acc = accuracy_score(pred1,y_test)
print(svc_acc)
print(confusion_matrix(pred1,y_test))

0.9833333333333333
[[19  0  0]
 [ 0 20  0]
 [ 0  1 20]]


In [82]:
from sklearn.linear_model import LogisticRegression  # its a classification
lr=LogisticRegression()
lr.fit(X_train,y_train)

LogisticRegression()

In [83]:
pred3 = lr.predict(X_test)
pred3

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       1, 2, 0, 0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1])

In [86]:
from sklearn.metrics import accuracy_score
lr_acc = accuracy_score(pred3,y_test)
print(lr_acc)
print(confusion_matrix(pred3,y_test))

0.9666666666666667
[[19  0  0]
 [ 0 20  1]
 [ 0  1 19]]
