In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv('C:\\Users\\Sweety\\Desktop\\anjali\\Machine Learning Internship\\mobile_price_range_data.csv')
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [3]:
data.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [4]:
data.shape

(2000, 21)

# Target variable

In [5]:
data['price_range'].value_counts()

1    500
2    500
3    500
0    500
Name: price_range, dtype: int64

# 1)Removing null values

In [6]:
data.isnull()

battery_power   blue  clock_speed  dual_sim     fc  four_g  int_memory  \
0             False  False        False     False  False   False       False   
1             False  False        False     False  False   False       False   
2             False  False        False     False  False   False       False   
3             False  False        False     False  False   False       False   
4             False  False        False     False  False   False       False   
...             ...    ...          ...       ...    ...     ...         ...   
1995          False  False        False     False  False   False       False   
1996          False  False        False     False  False   False       False   
1997          False  False        False     False  False   False       False   
1998          False  False        False     False  False   False       False   
1999          False  False        False     False  False   False       False   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width    ram   sc_h  \
0     False      False    False  ...      False     False  False  False   
1     False      False    False  ...      False     False  False  False   
2     False      False    False  ...      False     False  False  False   
3     False      False    False  ...      False     False  False  False   
4     False      False    False  ...      False     False  False  False   
...     ...        ...      ...  ...        ...       ...    ...    ...   
1995  False      False    False  ...      False     False  False  False   
1996  False      False    False  ...      False     False  False  False   
1997  False      False    False  ...      False     False  False  False   
1998  False      False    False  ...      False     False  False  False   
1999  False      False    False  ...      False     False  False  False   

       sc_w  talk_time  three_g  touch_screen   wifi  price_range  
0     False      False    False         False  False        False  
1     False      False    False         False  False        False  
2     False      False    False         False  False        False  
3     False      False    False         False  False        False  
4     False      False    False         False  False        False  
...     ...        ...      ...           ...    ...          ...  
1995  False      False    False         False  False        False  
1996  False      False    False         False  False        False  
1997  False      False    False         False  False        False  
1998  False      False    False         False  False        False  
1999  False      False    False         False  False        False  

[2000 rows x 21 columns]

In [7]:
data.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

# Handling Duplicates

In [8]:
data.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [9]:
data.duplicated().sum()

0

In [10]:
data.drop_duplicates(inplace=True)
data.duplicated().sum()

0

# Checking Datatypes

In [11]:
data.dtypes

battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
price_range        int64
dtype: object

# Selecting dependent(x) and independent(y) variables:

In [12]:
x=data.drop('price_range',axis=1)
y=data['price_range']
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(2000, 20)
(2000,)


# 2)splitting data into training and test data

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
print(2000*0.25)

500.0


In [15]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1500, 20)
(500, 20)
(1500,)
(500,)


# Confusion Matrix

In [16]:
from sklearn.metrics import confusion_matrix,classification_report


In [17]:
def eval_model(ytest,ypred):
    cm=confusion_matrix(ytest,ypred)
    print(cm)
    print(classification_report(ytest,ypred))


In [18]:
def mscore(model):
    print('Training score',model.score(x_train,y_train))
    print('Training score',model.score(x_test,y_test))

# 3)Apply the following models on the training dataset and generate the predicted value for
the test dataset

# a) Logistic Regression

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
a = LogisticRegression(max_iter=1000000,solver='liblinear')
a.fit(x_train,y_train)



LogisticRegression(max_iter=1000000, solver='liblinear')

In [21]:
mscore(a)

Training score 0.794
Training score 0.786


In [22]:
ypred_a=a.predict(x_test)
eval_model(y_test,ypred_a)

[[123   7   2   0]
 [ 13  72  33   0]
 [  0  24  72  24]
 [  0   0   4 126]]
              precision    recall  f1-score   support

           0       0.90      0.93      0.92       132
           1       0.70      0.61      0.65       118
           2       0.65      0.60      0.62       120
           3       0.84      0.97      0.90       130

    accuracy                           0.79       500
   macro avg       0.77      0.78      0.77       500
weighted avg       0.78      0.79      0.78       500



# b) KNN Classification

In [23]:
from sklearn.neighbors import KNeighborsClassifier

In [24]:
b=KNeighborsClassifier(n_neighbors=23)
b.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=23)

In [25]:
mscore(b)

Training score 0.942
Training score 0.94


In [26]:
ypred_b=b.predict(x_test)
eval_model(y_test,ypred_b)

[[128   4   0   0]
 [  5 112   1   0]
 [  0   9 107   4]
 [  0   0   7 123]]
              precision    recall  f1-score   support

           0       0.96      0.97      0.97       132
           1       0.90      0.95      0.92       118
           2       0.93      0.89      0.91       120
           3       0.97      0.95      0.96       130

    accuracy                           0.94       500
   macro avg       0.94      0.94      0.94       500
weighted avg       0.94      0.94      0.94       500



# c) SVM Classifier with linear and rbf kernel


In [27]:
import matplotlib.pyplot as plt
from mlxtend.plotting import plot_decision_regions

In [28]:
from sklearn import datasets

In [29]:
from sklearn.svm import SVC

In [30]:
c = SVC(kernel='linear',C=1)
c.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [31]:
mscore(c)

Training score 0.992
Training score 0.97


In [32]:
ypred_c=c.predict(x_test)
eval_model(y_test,ypred_c)

[[127   5   0   0]
 [  1 117   0   0]
 [  0   3 112   5]
 [  0   0   1 129]]
              precision    recall  f1-score   support

           0       0.99      0.96      0.98       132
           1       0.94      0.99      0.96       118
           2       0.99      0.93      0.96       120
           3       0.96      0.99      0.98       130

    accuracy                           0.97       500
   macro avg       0.97      0.97      0.97       500
weighted avg       0.97      0.97      0.97       500



# d) Decision Tree Classifier

In [33]:
from sklearn.tree import DecisionTreeClassifier

In [34]:
d = DecisionTreeClassifier(criterion='entropy',max_depth=6)
d.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=6)

In [35]:
mscore(d)

Training score 0.922
Training score 0.864


In [36]:
ypred_d=d.predict(x_test)
eval_model(y_test,ypred_d)

[[121  11   0   0]
 [  6  96  16   0]
 [  0   9  97  14]
 [  0   0  12 118]]
              precision    recall  f1-score   support

           0       0.95      0.92      0.93       132
           1       0.83      0.81      0.82       118
           2       0.78      0.81      0.79       120
           3       0.89      0.91      0.90       130

    accuracy                           0.86       500
   macro avg       0.86      0.86      0.86       500
weighted avg       0.87      0.86      0.86       500



# e) Random Forest Classifier

In [37]:
from sklearn.ensemble import RandomForestClassifier

In [38]:
e = RandomForestClassifier(n_estimators=90,criterion='entropy',max_depth=6)
e.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=6, n_estimators=90)

In [39]:
mscore(e)

Training score 0.944
Training score 0.852


In [40]:
ypred_e=e.predict(x_test)
eval_model(y_test,ypred_e)

[[125   7   0   0]
 [  9  95  14   0]
 [  0  20  85  15]
 [  0   0   9 121]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94       132
           1       0.78      0.81      0.79       118
           2       0.79      0.71      0.75       120
           3       0.89      0.93      0.91       130

    accuracy                           0.85       500
   macro avg       0.85      0.85      0.85       500
weighted avg       0.85      0.85      0.85       500



In [41]:
print(ypred_e)

[0 2 1 3 1 2 2 0 3 1 0 0 2 3 2 2 3 3 1 0 0 1 1 1 0 1 3 2 2 0 0 0 3 0 1 1 3
 0 3 0 2 3 2 0 3 3 2 0 3 1 3 1 0 0 0 0 1 3 0 0 1 3 3 2 0 0 3 3 1 2 2 3 0 1
 3 0 0 3 2 2 3 2 1 0 1 3 2 3 3 0 3 3 2 1 3 2 2 3 2 1 0 0 1 0 0 3 2 0 1 1 0
 0 3 1 3 2 2 3 0 2 1 3 2 1 3 3 0 3 1 2 3 0 2 2 0 3 1 0 0 2 3 0 2 2 0 0 0 1
 2 2 3 1 1 0 2 2 0 1 0 2 2 3 3 2 1 0 1 2 2 3 3 1 1 0 3 1 1 2 0 0 0 0 0 0 3
 2 0 3 0 0 0 0 1 3 3 1 0 1 2 1 1 2 2 3 2 3 1 2 0 0 0 1 1 1 3 1 0 2 2 1 3 1
 3 0 0 2 1 3 0 0 1 0 1 3 2 1 1 3 3 0 2 3 2 3 0 3 1 2 3 3 2 1 1 3 3 1 3 3 3
 3 3 0 1 2 2 2 2 0 2 3 2 2 2 1 0 2 0 2 3 1 3 1 0 3 1 2 0 0 3 0 1 2 3 3 3 1
 1 0 1 3 3 0 1 1 2 0 3 3 2 3 1 3 2 0 2 1 2 1 0 0 1 3 3 3 1 0 1 0 2 2 2 0 3
 3 2 1 3 0 0 3 1 3 2 0 1 1 2 1 2 3 1 0 0 3 3 0 3 0 0 1 0 0 2 2 2 3 0 3 2 2
 3 3 3 2 1 2 0 3 2 3 3 0 1 3 1 3 3 3 0 0 2 3 0 0 2 3 1 1 1 2 1 3 0 3 1 2 0
 0 1 0 1 0 2 0 1 3 3 1 1 1 3 1 0 3 1 0 0 3 0 1 0 0 1 3 3 0 2 1 1 1 2 3 1 2
 0 2 0 0 3 3 0 2 2 1 3 1 1 0 1 3 1 0 3 1 0 0 3 2 3 2 0 3 1 0 1 2 3 2 1 1 0
 1 2 2 1 1 1 3 1 2 0 3 3 

# 4)Predict the price range for test data

In [42]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
data=pd.read_csv('C:\\Users\\Sweety\\Desktop\\anjali\\Machine Learning Internship\\mobile_price_range_data.csv')
data

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7   
1              1021     1          0.5         1   0       1          53   
2               563     1          0.5         1   2       1          41   
3               615     1          2.5         0   0       0          10   
4              1821     1          1.2         0  13       1          44   
...             ...   ...          ...       ...  ..     ...         ...   
1995            794     1          0.5         1   0       1           2   
1996           1965     1          2.6         1   0       0          39   
1997           1911     0          0.9         1   1       1          36   
1998           1512     0          0.9         0   4       1          46   
1999            510     1          2.0         1   5       1          45   

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7   
1       0.7        136        3  ...        905      1988  2631    17     3   
2       0.9        145        5  ...       1263      1716  2603    11     2   
3       0.8        131        6  ...       1216      1786  2769    16     8   
4       0.6        141        2  ...       1208      1212  1411     8     2   
...     ...        ...      ...  ...        ...       ...   ...   ...   ...   
1995    0.8        106        6  ...       1222      1890   668    13     4   
1996    0.2        187        4  ...        915      1965  2032    11    10   
1997    0.7        108        8  ...        868      1632  3057     9     1   
1998    0.1        145        5  ...        336       670   869    18    10   
1999    0.9        168        6  ...        483       754  3919    19     4   

      talk_time  three_g  touch_screen  wifi  price_range  
0            19        0             0     1            1  
1             7        1             1     0            2  
2             9        1             1     0            2  
3            11        1             0     0            2  
4            15        1             1     0            1  
...         ...      ...           ...   ...          ...  
1995         19        1             1     0            0  
1996         16        1             1     1            2  
1997          5        1             1     0            3  
1998         19        1             1     1            0  
1999          2        1             1     1            3  

[2000 rows x 21 columns]

In [44]:
data.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [45]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [46]:
data.describe()

battery_power       blue  clock_speed     dual_sim           fc  \
count    2000.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     0.4950     1.522250     0.509500     4.309500   
std       439.418206     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       851.750000     0.0000     0.700000     0.000000     1.000000   
50%      1226.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.250000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  ...  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  ...   
mean      0.521500    32.046500     0.501750   140.249000     4.520500  ...   
std       0.499662    18.145715     0.288416    35.399655     2.287837  ...   
min       0.000000     2.000000     0.100000    80.000000     1.000000  ...   
25%       0.000000    16.000000     0.200000   109.000000     3.000000  ...   
50%       1.000000    32.000000     0.500000   141.000000     4.000000  ...   
75%       1.000000    48.000000     0.800000   170.000000     7.000000  ...   
max       1.000000    64.000000     1.000000   200.000000     8.000000  ...   

         px_height     px_width          ram         sc_h         sc_w  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    645.108000  1251.515500  2124.213000    12.306500     5.767000   
std     443.780811   432.199447  1084.732044     4.213245     4.356398   
min       0.000000   500.000000   256.000000     5.000000     0.000000   
25%     282.750000   874.750000  1207.500000     9.000000     2.000000   
50%     564.000000  1247.000000  2146.500000    12.000000     5.000000   
75%     947.250000  1633.000000  3064.500000    16.000000     9.000000   
max    1960.000000  1998.000000  3998.000000    19.000000    18.000000   

         talk_time      three_g  touch_screen         wifi  price_range  
count  2000.000000  2000.000000   2000.000000  2000.000000  2000.000000  
mean     11.011000     0.761500      0.503000     0.507000     1.500000  
std       5.463955     0.426273      0.500116     0.500076     1.118314  
min       2.000000     0.000000      0.000000     0.000000     0.000000  
25%       6.000000     1.000000      0.000000     0.000000     0.750000  
50%      11.000000     1.000000      1.000000     1.000000     1.500000  
75%      16.000000     1.000000      1.000000     1.000000     2.250000  
max      20.000000     1.000000      1.000000     1.000000     3.000000  

[8 rows x 21 columns]

In [47]:
X = data.drop('price_range',axis=1)
y = data['price_range']

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,y,test_size=0.1,random_state=101)

In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [50]:
X_train

array([[-1.62737257, -0.98675438, -1.01271559, ..., -1.78222729,
        -1.00892875, -0.99888951],
       [-0.75199354,  1.01342342,  0.58093235, ..., -1.78222729,
         0.99115027, -0.99888951],
       [-0.20630271,  1.01342342,  0.70352065, ...,  0.56109566,
        -1.00892875,  1.00111173],
       ...,
       [ 0.69636086,  1.01342342, -0.03200917, ...,  0.56109566,
        -1.00892875, -0.99888951],
       [ 0.83733099, -0.98675438, -1.2578922 , ...,  0.56109566,
        -1.00892875,  1.00111173],
       [ 0.4144206 , -0.98675438, -0.39977408, ...,  0.56109566,
         0.99115027,  1.00111173]])

In [51]:
 X_test

array([[ 0.28481903, -0.98675438, -1.2578922 , ...,  0.56109566,
        -1.00892875, -0.99888951],
       [-1.44092821, -0.98675438, -1.2578922 , ...,  0.56109566,
         0.99115027,  1.00111173],
       [-1.49322358, -0.98675438, -0.15459747, ...,  0.56109566,
        -1.00892875,  1.00111173],
       ...,
       [-0.55418061,  1.01342342,  0.33575574, ...,  0.56109566,
        -1.00892875, -0.99888951],
       [ 0.09610095, -0.98675438, -0.89012729, ...,  0.56109566,
         0.99115027,  1.00111173],
       [-1.60690917, -0.98675438,  1.07128556, ...,  0.56109566,
         0.99115027, -0.99888951]])

In [52]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(X_train , Y_train)

DecisionTreeClassifier()

In [53]:
pred = dtc.predict(X_test)
pred

array([1, 1, 2, 1, 0, 1, 2, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 3, 1,
       2, 3, 2, 2, 2, 1, 0, 0, 2, 3, 0, 0, 3, 0, 0, 0, 1, 1, 1, 2, 3, 2,
       2, 1, 1, 3, 3, 1, 0, 0, 2, 3, 3, 2, 0, 3, 3, 3, 2, 2, 3, 1, 3, 2,
       0, 0, 0, 2, 1, 2, 3, 2, 1, 3, 3, 2, 0, 2, 0, 0, 2, 1, 2, 2, 2, 1,
       0, 0, 3, 3, 0, 2, 0, 3, 2, 0, 2, 3, 0, 2, 2, 3, 0, 2, 0, 0, 2, 0,
       1, 0, 3, 2, 2, 2, 1, 3, 2, 0, 3, 3, 2, 3, 1, 3, 3, 2, 1, 1, 1, 0,
       1, 1, 0, 2, 3, 0, 2, 3, 1, 3, 0, 1, 0, 0, 1, 3, 3, 0, 2, 1, 3, 2,
       3, 3, 2, 0, 3, 1, 2, 2, 2, 2, 1, 2, 1, 1, 3, 3, 1, 2, 0, 3, 1, 3,
       1, 2, 2, 1, 2, 1, 0, 1, 3, 3, 1, 2, 1, 3, 1, 0, 2, 3, 0, 3, 0, 0,
       3, 0], dtype=int64)

# 5)Compute Confusion matrix and classification report for each of these models.

In [54]:
from sklearn.metrics import accuracy_score, confusion_matrix
dtc_acc = accuracy_score(pred,Y_test)
print(dtc_acc)
print(confusion_matrix(pred,Y_test))

0.83
[[44  3  0  0]
 [ 6 39  7  0]
 [ 0  4 45  4]
 [ 0  0 10 38]]


# classification report

In [55]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30)
X = data.drop('price_range',axis=1)
y = data['price_range']

In [57]:
classifier_tree = DecisionTreeClassifier()
y_predict = classifier_tree.fit(X_train, y_train).predict(X_test)

In [58]:
clf = MultinomialNB()
clf.fit(X_train,y_train)
predictions = clf.predict(x_test)

# Classification Report
from sklearn.metrics import classification_report
print(classification_report(ypred_e, predictions))

              precision    recall  f1-score   support

           0       0.75      0.75      0.75       134
           1       0.53      0.50      0.51       122
           2       0.41      0.40      0.40       108
           3       0.64      0.68      0.66       136

    accuracy                           0.59       500
   macro avg       0.58      0.58      0.58       500
weighted avg       0.59      0.59      0.59       500



# 6)Report the model with the best accuracy.

In [59]:
from sklearn.svm import SVC
knn=SVC()
knn.fit(X_train,y_train)


SVC()

In [60]:
pred1 = knn.predict(X_test)
pred1

array([0, 3, 1, 1, 1, 0, 1, 3, 3, 1, 1, 3, 0, 3, 0, 1, 2, 1, 3, 2, 1, 2,
       1, 3, 1, 1, 3, 2, 2, 1, 1, 0, 3, 0, 1, 1, 1, 1, 3, 1, 1, 1, 1, 3,
       2, 1, 0, 0, 0, 0, 0, 1, 3, 3, 1, 2, 0, 3, 0, 3, 1, 3, 0, 2, 2, 1,
       0, 3, 0, 1, 0, 0, 1, 2, 3, 1, 0, 1, 1, 0, 0, 0, 3, 2, 1, 2, 3, 2,
       2, 0, 3, 1, 0, 1, 0, 1, 1, 0, 2, 3, 2, 3, 0, 1, 0, 1, 3, 0, 0, 2,
       3, 1, 0, 3, 3, 0, 0, 2, 0, 2, 3, 1, 0, 3, 0, 1, 3, 3, 2, 2, 0, 1,
       3, 3, 1, 2, 1, 2, 3, 3, 0, 3, 1, 3, 2, 0, 3, 1, 0, 3, 1, 1, 0, 1,
       0, 3, 0, 3, 3, 0, 0, 3, 1, 0, 0, 2, 1, 1, 1, 0, 3, 2, 0, 0, 3, 3,
       0, 2, 0, 3, 2, 1, 2, 3, 3, 2, 3, 2, 1, 3, 1, 1, 2, 1, 2, 0, 0, 3,
       1, 0, 0, 3, 2, 0, 2, 1, 3, 1, 2, 0, 0, 1, 0, 2, 1, 1, 1, 2, 3, 3,
       3, 1, 0, 0, 1, 3, 1, 1, 0, 0, 3, 3, 3, 3, 3, 1, 1, 1, 0, 3, 0, 2,
       3, 2, 1, 0, 0, 3, 2, 0, 2, 1, 3, 1, 1, 1, 3, 0, 0, 2, 3, 1, 2, 1,
       1, 3, 2, 3, 2, 2, 2, 3, 1, 0, 2, 0, 1, 3, 2, 3, 0, 2, 3, 0, 2, 2,
       2, 3, 0, 0, 3, 1, 0, 1, 1, 0, 3, 1, 0, 2, 0,

In [61]:
from sklearn.metrics import accuracy_score
svc_acc = accuracy_score(pred1,y_test)
print(svc_acc)
print(confusion_matrix(pred1,y_test))

0.9533333333333334
[[150   5   0   0]
 [  3 142   4   0]
 [  0   2 128   3]
 [  0   0  11 152]]


In [62]:
from sklearn.linear_model import LogisticRegression  # its a classification
lr=LogisticRegression()
lr.fit(X_train,y_train)

C:\Users\Sweety\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [63]:
pred2 = lr.predict(X_test)
pred2

array([0, 3, 0, 0, 1, 0, 3, 3, 3, 2, 1, 3, 0, 3, 0, 2, 2, 1, 3, 1, 1, 3,
       0, 1, 0, 2, 3, 1, 2, 1, 1, 1, 3, 0, 1, 1, 1, 3, 3, 2, 1, 2, 1, 2,
       3, 1, 0, 0, 0, 0, 0, 1, 2, 2, 1, 2, 1, 3, 0, 3, 2, 3, 0, 3, 2, 1,
       1, 3, 0, 1, 0, 0, 2, 2, 3, 1, 0, 2, 3, 0, 0, 0, 2, 2, 3, 1, 3, 1,
       3, 0, 3, 1, 0, 2, 0, 1, 2, 0, 3, 3, 3, 3, 0, 1, 0, 2, 2, 0, 0, 2,
       2, 1, 0, 2, 3, 0, 0, 3, 0, 2, 3, 0, 0, 3, 0, 1, 3, 3, 1, 3, 0, 1,
       2, 3, 1, 3, 1, 1, 2, 2, 0, 3, 1, 3, 2, 0, 3, 2, 0, 3, 2, 1, 0, 1,
       1, 3, 0, 3, 3, 0, 0, 3, 1, 0, 0, 2, 1, 3, 1, 0, 3, 2, 0, 0, 3, 3,
       1, 3, 1, 3, 2, 0, 3, 3, 3, 2, 3, 3, 0, 3, 3, 1, 2, 2, 1, 0, 0, 2,
       1, 0, 1, 3, 2, 0, 2, 2, 3, 1, 3, 0, 0, 1, 0, 2, 1, 0, 1, 2, 3, 2,
       3, 2, 0, 0, 1, 3, 1, 1, 0, 1, 3, 2, 3, 3, 3, 0, 0, 1, 0, 3, 2, 1,
       2, 1, 2, 0, 0, 3, 1, 0, 3, 1, 3, 0, 1, 1, 3, 1, 0, 3, 3, 2, 3, 1,
       2, 2, 2, 2, 1, 2, 3, 3, 1, 0, 2, 0, 2, 2, 2, 3, 0, 2, 3, 0, 2, 3,
       3, 3, 0, 0, 3, 1, 0, 0, 1, 0, 3, 0, 0, 2, 0,

In [64]:
from sklearn.metrics import accuracy_score
lr_acc = accuracy_score(pred2,y_test)
print(lr_acc)
print(confusion_matrix(pred2,y_test))

0.6566666666666666
[[123  26   0   0]
 [ 29  85  37   1]
 [  1  33  66  34]
 [  0   5  40 120]]
